export type FeatureNames = 'nextQueries'
  | 'topRecommendations'
  | 'sectionRecommendations'
  | 'clicksRecommendations'
  | 'queriesRecommendations'
  | 'userRecommendations'
  | 'relatedTags'
  | 'suggestions'
  | 'search'
  | 'searchById'
  | 'track';
