version: 2
updates:

  # Maintain dependencies for the root package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/Madrid"
