<template>
  <svg
    id="e4kx3Cn5VZF1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 300 300"
    shape-rendering="geometricPrecision"
    text-rendering="geometricPrecision"
  >
    <g transform="translate(150, 150)">
      <polygon
        points="0,-100 21.213,-21.213 100,0 21.213,21.213 0,100 -21.213,21.213 -100,0 -21.213,-21.213"
        fill="#243d48"
        stroke="#243d48"
        stroke-width="10"
        stroke-linejoin="round"
      >
        <animateTransform
          attributeName="transform"
          attributeType="XML"
          type="scale"
          values="0;1;1;0"
          keyTimes="0;0.2;0.8;1"
          calcMode="linear"
          dur="2.5s"
          repeatCount="indefinite"
          additive="sum"
        />
        <animateTransform
          attributeName="transform"
          attributeType="XML"
          type="rotate"
          values="0;180;180;360"
          keyTimes="0;0.2;0.8;1"
          calcMode="linear"
          dur="2.5s"
          repeatCount="indefinite"
          additive="sum"
        />
      </polygon>
      <ellipse
        id="e4kx3Cn5VZF3"
        cx="70"
        cy="-70"
        rx="27.5"
        ry="27.5"
        fill="#5e7782"
        stroke-width="0"
      >
        <animateTransform
          attributeName="transform"
          attributeType="XML"
          type="scale"
          values="0;1;1;0"
          keyTimes="0;0.2;0.80;1"
          dur="2.5s"
          begin="0.1s"
          repeatCount="indefinite"
          additive="sum"
        />
        <animateTransform
          attributeName="transform"
          attributeType="XML"
          type="translate"
          values="-60,00;0,0;0,0;-60,-70"
          keyTimes="0;0.2;0.80;1"
          calcMode="linear"
          dur="2.5s"
          begin="0.1s"
          repeatCount="indefinite"
          additive="sum"
        />
      </ellipse>
    </g>
  </svg>
</template>
