name: Release alpha version
description: Runs npm script to release alpha version and pushes tags to github
inputs:
  npm_token:
    description: Token to push code to npm
    required: true
  github_token:
    description: Token to push code to github
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure git user
      run: |
        git config --local user.email "x@empathy.co"
        git config --local user.name "empathy/x"
      shell: bash

    - name: Configure npm auth
      run: |
        npm config set registry="https://registry.npmjs.org/"
        npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}

    - name: Publish release
      run: |
        git restore ./pnpm-lock.yaml
        
        # Capture output and error from pnpm run release:alpha
        if ! output=$(pnpm run release:alpha 2>&1); then
          exit_code=$?
          
          # Check if the error is related to NPM authentication (E404 from lerna)
          if echo "$output" | grep -q "lerna ERR! E404 Not found"; then
            echo ""
            echo "🔴 ================================================================================================"
            echo "🔴 CRITICAL ERROR: NPM_TOKEN_GRANULAR_ACCESS REPOSITORY SECRET HAS EXPIRED"
            echo "🔴 ================================================================================================"
            echo ""
            echo "The release failed because the NPM_TOKEN_GRANULAR_ACCESS repository secret has expired."
            echo ""
            echo "👉 ACTION REQUIRED:"
            echo "   1. Open a new Jira ticket to the Platform Team"
            echo "   2. Clone this ticket: https://searchbroker.atlassian.net/browse/OPS-10807"
            echo "   3. Request NPM_TOKEN_GRANULAR_ACCESS secret renewal for this repository"
            echo "   4. Once the Platform Team renews the token, re-run this workflow"
            echo ""
            echo "🔴 ================================================================================================"
            echo ""
          fi
          
          # Print the original error output for additional context
          echo "Original error output:"
          echo "$output"
          
          # Exit with the original error code
          exit $exit_code
        fi
      shell: bash

    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        tags: true
