name: Release alpha version
description: Runs npm script to release alpha version and pushes tags to github
inputs:
  github_token:
    description: Token to push code to github
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure git user
      run: |
        git config --local user.email "x@empathy.co"
        git config --local user.name "empathy/x"
      shell: bash

    - name: Publish release
      run: |
        git restore ./pnpm-lock.yaml
        pnpm run release:alpha
      shell: bash

    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        tags: true
