---
name: Feature request
about: Suggest an idea for this project
title: "[FEATURE]: "
labels: "feature,enhancement"
assignees: ""

---
body:
   - type: markdown
     attributes:
      value: |
      When suggesting a new feature for the Interface X project, submit your idea as a [user story](https://en.wikipedia.org/wiki/User_story) and provide as much information as possible on how you would solve it, so the team can assess and analyze your idea.
      When defining your new feature, you need to consider it from two points of view: 
      - the **Final User** who accesses the commerce website that uses the component.
      - the **Developer User** who is going to use the component to build a website. 

      Depending on the feature, you may need to consider one or both.
   - type: textarea
     id: suggestion
     attributes:
      label: How can the project be improved?
      description: Describe the problem encountered by the user, what they need to solve it, and what they expect.
      placeholder: Provide a brief description of the interface and its expected behavior. Include details of other requirements that the feature must cover, such as dependencies and actions covered by other services, and other needs.

      Example for the History Queries module:
      * Display a list of search queries already performed by the user.
      * Each search query of the list has a button to delete it from the list.
      * The list of search queries must be maintained in the same device over time, even when the tab is closed.
      * If there are no search queries, then nothing should be displayed. 
   - type: textarea
    id: solution
    attributes:
     label: How can this be solved?
     description: Explain the different interactions of the user. 
     placeholder: Example for the History Queries module:
     * When the user clicks on an item of the list, then that search query is performed.
     * When the user clicks on the delete button, then the search query is removed from the list.    
   - type: textarea
      id: proposal
      attributes:
       label: Proposed solution
       placeholder: Simple version of HTML expected, if needed. Example:
       ```
        <ul class="queries-list">
         <li class="queries-list__item">
             <button class="queries-list__delete">X</button>
             <button class="queries-list__query">lego</button>
         </li>
         <li class="queries-list__item">
             <button class="queries-list__delete">X</button>
             <button class="queries-list__query">playmobil</button>
        </li>
        </ul>
      ```
      (!) It is not strictly necessary to follow this layout. This is just an example to get you started
   - type: textarea
      id: customizations
      attributes:
       label: Customizations supported
       description: Provide ideas for customizations that can be performed by the developer 
       placeholder: Example for the History Queries module:
      * Change the content of each search query
      * Change the content of each delete button
      * Change the complete content of the item
      * Add different animation to items
      * Change the number of the search queries to show
   - type: textarea
     id: additionalinfo
     attributes:
       label: Additional information
       description: Provide as much supporting information as possible. Including attachments will help us to better understand your feature request and requirements.
       placeholder: Include supporting documentation
       Example: 
       * designs
       * diagrams
       * videos
       * Confluence links
       * real example
   - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g email@example.com
    validations:
      required: false
   - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](./code_of_conduct.md)
      options:
      - label: I agree to follow this project's Code of Conduct
          required: true