name: Run e2e tests
description: Runs e2e tests

runs:
  using: 'composite'

  steps:
    - name: Cypress run X Components
      uses: cypress-io/github-action@v6
      with:
        install: false
        browser: chrome
        start: npm run preview
        working-directory: packages/x-components

    - name: Cypress run X Components component
      uses: cypress-io/github-action@v6
      with:
        install: false
        browser: chrome
        start: npm run preview
        working-directory: packages/x-components
        component: true
