export * from './actions/fetch-and-save-related-tags.action'
export * from './actions/fetch-related-tags.action'
export * from './actions/toggle-related-tag.action'
export * from './emitters'
export { query as relatedTagsQuery } from './getters/query.getter'
export * from './getters/related-tags.getter'
export { request as relatedTagsRequest } from './getters/request.getter'
export * from './module'
export * from './types'
