name: Install
description: Checkouts the repo and installs dependencies

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: 22

    # Install pnpm because it is not included in our container image
    - name: install pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      with:
        version: 9.15.9
        run_install: true

    - name: Build
      shell: bash
      run: pnpm run build

    - name: Pack
      shell: bash
      run: pnpm run pack
