name: Install
description: Checkouts the repo and installs dependencies

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: 18

    # Install pnpm because it is not included in our container image
    - name: install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        version: 8

    - name: Install deps
      uses: cypress-io/github-action@v5
      with:
        runTests: false
