name: Install
description: Checkouts the repo and installs dependencies

runs:
  using: 'composite'
  steps:
    - name: Set Node version
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version-file: .nvmrc

    # Install pnpm because it is not included in our container image
    - name: Install PNPM
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        version: 9.15.9
        run_install: true

    - name: Build
      shell: sh
      run: pnpm run build

    - name: Pack
      shell: sh
      run: pnpm run pack
