name: Install
description: Checkouts the repo and installs dependencies

runs:
  using: 'composite'
  steps:
    - name: Set Node version
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: .nvmrc

    # Install pnpm because it is not included in our container image
    - name: Install PNPM
      uses: pnpm/action-setup@v5.0.0
      with:
        version: 9.15.9
        run_install: true

    - name: Build
      shell: sh
      run: pnpm run build

    - name: Pack
      shell: sh
      run: pnpm run pack
