name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      # Use GitHub App token as a workaround to allow bypassing branch-protection rules
      # Only for internal contributors or when secrets are available
      # https://github.com/orgs/community/discussions/13836#discussioncomment-8535364
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        if: ${{ vars.GH_TOKENS_APP_ID != '' }}
        id: app-token
        with:
          app-id: ${{ vars.GH_TOKENS_APP_ID }}
          private-key: ${{ secrets.GH_TOKENS_APP_PRIVATE_KEY }}

      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.app-token.outputs.token || github.token }}
          fetch-depth: 0

      - name: Install Build & Pack
        uses: ./.github/actions/install

      - name: Linter
        run: pnpm run lint:check

      - name: Prettier
        run: pnpm run format:check

      - name: Typecheck
        run: pnpm run typecheck

      - name: Tests
        run: pnpm run test:unit
