name: Prepare stable release
on: [workflow_dispatch]
jobs:
  prepare-release:
    runs-on: [self-hosted, linux, x64, platform, vm]
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: configure git user
        run: |
          git config --local user.email "x@empathy.co"
          git config --local user.name "empathy/x"

      - name: prepare the release
        run: pnpm run prepare-release:stable

      - name: create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          token: ${{ github.token }}
          commit-message: "chore(release): prepare stable release"
          committer: Interface X <x@empathy.co>
          title: "chore(release): prepare stable release"
          body: Release preparation
          branch: release
          delete-branch: true
