name: Pull Request Stats

on:
  pull_request:
    types: [opened,edited]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 90
          charts: true
          sort-by: 'COMMENTS'
