name: Release
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Create .npmrc file with authorization token
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install lerna and all packages
        run: npm install
      - name: Build all packages
        run: npm run build
      - name: Run linter in all packages
        run: npm run lint
      - name: Run tests in all packages
        run: npm run test
      - name: Retrieve current commit tags
        run: echo "COMMIT_TAGS=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - name: Display tags
        run: echo $COMMIT_TAGS
      - name: Publish the changed packages only if there are tags
        if: ${{ github.event_name == 'push' && github.ref == 'develop' && $COMMIT_TAGS != '' }}
        run: echo Publishing packages...
      #  run: npm run publish
