name: Release alpha version on demand
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'
jobs:
  release-alpha:
    runs-on: [self-hosted, linux, x64, platform, vm]
    permissions:
      id-token: write
      contents: read

    steps:
      # Use GitHub App token as a workaround to allow bypassing branch-protection rules
      # https://github.com/orgs/community/discussions/13836#discussioncomment-8535364
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ vars.GH_TOKENS_APP_ID }}
          private-key: ${{ secrets.GH_TOKENS_APP_PRIVATE_KEY }}

      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: execute release-alpha action
        uses: ./.github/actions/release-alpha
        with:
          npm_token: ${{ secrets.NPM_TOKEN_GRANULAR_ACCESS }}
          github_token: ${{ steps.app-token.outputs.token }}
