name: Release
on:
  push:
    branches:
      - main
    tags:
      - @empathyco/*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Prepare .npmrc file to release
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install lerna and all packages
        run: npm install
      - name: Build all packages
        run: npm run build
      - name: Run linter in all packages
        run: npm run lint
      - name: Run tests in all packages
        run: npm run test
      #- name: Publish the changed packages
      #  run: npm run publish

